-- BMI / SEGAK SKSA — isolated storage inside the existing Portal Koku Supabase project.
-- This migration creates ONLY segak_* objects. It does NOT ALTER Portal Koku tables.

create extension if not exists pgcrypto;

create table if not exists public.segak_student_profiles (
  student_id uuid primary key,
  full_name_cache text not null default '',
  gender text null check (gender is null or gender in ('LELAKI','PEREMPUAN')),
  mykid text null,
  guardian_phone text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.segak_records (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null,
  session_year integer not null check (session_year between 2000 and 2100),
  class_id uuid null,
  class_code text not null,
  class_name text not null default '',
  year_level integer not null check (year_level between 1 and 6),
  pengisian smallint not null check (pengisian in (1,2)),
  age smallint null check (age is null or age between 5 and 19),
  height_cm numeric(5,1) null check (height_cm is null or height_cm between 50 and 250),
  weight_kg numeric(5,1) null check (weight_kg is null or weight_kg between 5 and 250),
  bmi numeric(5,1) null,
  bmi_status text null,
  step_pulse integer null check (step_pulse is null or step_pulse between 20 and 300),
  push_ups integer null check (push_ups is null or push_ups between 0 and 200),
  curl_ups integer null check (curl_ups is null or curl_ups between 0 and 25),
  sit_reach_cm integer null check (sit_reach_cm is null or sit_reach_cm between 0 and 100),
  total_score smallint null check (total_score is null or total_score between 4 and 20),
  grade text null check (grade is null or grade in ('A','B','C','D','E','F')),
  fitness_status text null,
  test_date date null,
  source text not null default 'webapp' check (source in ('webapp','legacy_sheet')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint segak_records_student_session_term_unique unique (student_id, session_year, pengisian)
);

create table if not exists public.segak_legacy_staging (
  id uuid primary key default gen_random_uuid(),
  session_year integer not null,
  class_code text not null,
  full_name text not null,
  normalized_name text not null,
  gender text null check (gender is null or gender in ('LELAKI','PEREMPUAN')),
  pengisian smallint not null default 1 check (pengisian in (1,2)),
  age smallint null,
  height_cm numeric(5,1) null,
  weight_kg numeric(5,1) null,
  step_pulse integer null,
  push_ups integer null,
  curl_ups integer null,
  sit_reach_cm integer null,
  test_date date null,
  migrated_student_id uuid null,
  migrated_at timestamptz null,
  created_at timestamptz not null default now(),
  constraint segak_legacy_staging_unique unique (session_year, class_code, normalized_name, pengisian)
);

create table if not exists public.segak_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.segak_audit_log (
  id bigint generated by default as identity primary key,
  action text not null,
  session_year integer null,
  class_code text null,
  student_id uuid null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.segak_settings(key,value)
values ('school_name','SEKOLAH KEBANGSAAN SUNGAI ABONG')
on conflict (key) do nothing;

-- app_password_sha256 is intentionally NOT committed to source control.
-- Configure it server-side in segak_settings before deploying segak-api on a new installation.

create index if not exists idx_segak_legacy_unmigrated
  on public.segak_legacy_staging(session_year,class_code)
  where migrated_student_id is null;
create index if not exists idx_segak_records_session_class_term
  on public.segak_records(session_year,class_code,pengisian);
create index if not exists idx_segak_records_student
  on public.segak_records(student_id);
create index if not exists idx_segak_records_year_level
  on public.segak_records(session_year,year_level);
create index if not exists idx_segak_audit_created_at
  on public.segak_audit_log(created_at desc);

create or replace function public.set_segak_updated_at()
returns trigger
language plpgsql
set search_path=public
as $$
begin
  new.updated_at=now();
  return new;
end;
$$;

drop trigger if exists trg_segak_profiles_updated_at on public.segak_student_profiles;
create trigger trg_segak_profiles_updated_at before update on public.segak_student_profiles
for each row execute function public.set_segak_updated_at();

drop trigger if exists trg_segak_records_updated_at on public.segak_records;
create trigger trg_segak_records_updated_at before update on public.segak_records
for each row execute function public.set_segak_updated_at();

drop trigger if exists trg_segak_settings_updated_at on public.segak_settings;
create trigger trg_segak_settings_updated_at before update on public.segak_settings
for each row execute function public.set_segak_updated_at();

alter table public.segak_student_profiles enable row level security;
alter table public.segak_records enable row level security;
alter table public.segak_settings enable row level security;
alter table public.segak_legacy_staging enable row level security;
alter table public.segak_audit_log enable row level security;

-- Browser access is intentionally blocked. Edge Function uses service_role server-side.
revoke all on public.segak_student_profiles from anon,authenticated;
revoke all on public.segak_records from anon,authenticated;
revoke all on public.segak_settings from anon,authenticated;
revoke all on public.segak_legacy_staging from anon,authenticated;
revoke all on public.segak_audit_log from anon,authenticated;

-- Deliberately no foreign keys to Portal Koku tables.
